### ISSUE TITLE
Bug with mysql

### ISSUE THREAD

**Issue by Lunatik934** [PikaMug/Quests#1475]
**What is your Quests version / build number (do _not_ say "latest")?**
4.0.0-rc.3
**Describe the problem and how to replicate it. Any console errors to post _using Pastebin.com_?**
https://hastebin.com/recobiyene.md
**If applicable, can you provide an example quest from quests.yml _using Pastebin.com_?**

**Comment by PikaMug** [comment]
Thanks for the report. Did you receive this error during normal play? Or were you converting data with [QuestsConverter](https://www.spigotmc.org/resources/questsconverter.86165/)?

**Comment by Lunatik934** [comment]
Yea when during normal play

**Comment by PikaMug** [comment]
@Lunatik934 Resolved in https://ci.codemc.io/job/PikaMug/job/Quests/169/

**Comment by Lunatik934** [comment]
`[14:21:42 WARN]: [Pool-worker-8] java.sql.SQLIntegrityConstraintViolationException: Column 'lastknownname' cannot be null
[14:21:42 WARN]: [Pool-worker-8]        at me.blackvein.quests.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
[14:21:42 WARN]: [Pool-worker-8]        at me.blackvein.quests.libs.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[14:21:42 WARN]: [Pool-worker-8]        at me.blackvein.quests.libs.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[14:21:42 WARN]: [Pool-worker-8]        at me.blackvein.quests.libs.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:637)
[14:21:42 WARN]: [Pool-worker-8]        at me.blackvein.quests.libs.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:418)
[14:21:42 WARN]: [Pool-worker-8]        at me.blackvein.quests.libs.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
[14:21:42 WARN]: [Pool-worker-8]        at me.blackvein.quests.libs.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
[14:21:42 WARN]: [Pool-worker-8]        at me.blackvein.quests.libs.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
[14:21:42 WARN]: [Pool-worker-8]        at me.blackvein.quests.storage.implementation.sql.SqlStorage.saveQuesterData(SqlStorage.java:206)
[14:21:42 WARN]: [Pool-worker-8]        at me.blackvein.quests.storage.Storage.lambda$saveQuesterData$3(Storage.java:101)
[14:21:42 WARN]: [Pool-worker-8]        at me.blackvein.quests.storage.Storage.lambda$makeFuture$1(Storage.java:59)
[14:21:42 WARN]: [Pool-worker-8]        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
[14:21:42 WARN]: [Pool-worker-8]        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
[14:21:42 WARN]: [Pool-worker-8]        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[14:21:42 WARN]: [Pool-worker-8]        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[14:21:42 WARN]: [Pool-worker-8]        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[14:21:42 WARN]: [Pool-worker-8]        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
`

**Comment by DeadlykillOfficial** [comment]
Open up your Database under table quests_players and then add manually allow null on `lastknownname` as shown on the picture
![image](https://user-images.githubusercontent.com/12415714/100545275-51293580-325b-11eb-90f7-63ad279559bd.png)

**Comment by PikaMug** [comment]
@Lunatik934 Sorry, I should have mentioned you'll need to drop and re-import your player data. The @DeadlykillOfficial works too, but any modules/plugins that depend on Quests for last known names may not like the null values.

**Comment by DeadlykillOfficial** [comment]
Even after dropping database tables and regenerating them . The Error persists. It turns out Quests always send null regardless of what's happening. Putting allow null on table does fix the issue.

**Comment by PikaMug** [comment]
@DeadlykillOfficial Looks like I forgot to link https://ci.codemc.io/job/PikaMug/job/Quests/170/

**Comment by DeadlykillOfficial** [comment]
I'm even using 171 and still drops errors unless Allow null

**Comment by PikaMug** [comment]
@DeadlykillOfficial Could you create a new ticket with an error from that build, please?
