### ISSUE TITLE
Bug console! 

### ISSUE THREAD

**Issue by brnxx** [PikaMug/Quests#913]
![image](https://user-images.githubusercontent.com/49076883/62828374-2543f580-bbbb-11e9-8c5d-50a64e2f47ad.png)
![image](https://user-images.githubusercontent.com/49076883/62828375-2c6b0380-bbbb-11e9-91b8-bb3326a49e1f.png)

![image](https://user-images.githubusercontent.com/49076883/62828370-18270680-bbbb-11e9-8f30-5f6c43f86fb4.png)
![image](https://user-images.githubusercontent.com/49076883/62828380-4efd1c80-bbbb-11e9-875c-df07d9a3e95c.png)

can anybody help me?

**Comment by PikaMug** [comment]
Thanks for your report. It seems you’re missing the last half of the error. Please post it in full or describe how to replicate the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brnxx** [comment]
> Thanks for your report. It seems you’re missing the last half of the error. Please post it in full or describe how to replicate the issue.

![image](https://user-images.githubusercontent.com/49076883/62828730-a99a7680-bbc3-11e9-9522-3baef208a6ef.png)
![image](https://user-images.githubusercontent.com/49076883/62828737-fbdb9780-bbc3-11e9-9fc7-974ae76f58b2.png)

 it's just these

**Comment by brnxx** [comment]
![image](https://user-images.githubusercontent.com/49076883/62828840-0303a500-bbc6-11e9-9a31-ec7b6468db2b.png)

**Comment by PikaMug** [comment]
Looks like this issue was resolved recently, so try https://ci.codemc.org/job/PikaMug/job/Quests/21/

Warning: The build linked above is experimental. Make sure to back up your Quests folder before attempting to use it. Alternatively, wait until the final release on Spigot.

**Comment by brnxx** [comment]
![image](https://user-images.githubusercontent.com/49076883/63055002-4e1a0280-bebb-11e9-819e-05b6357bf1ca.png)
![image](https://user-images.githubusercontent.com/49076883/63055052-6be76780-bebb-11e9-947e-309963479f83.png)
![image](https://user-images.githubusercontent.com/49076883/63055058-70ac1b80-bebb-11e9-9e9a-121484fe3ccb.png)


The console bug is back, friend.

**Comment by PikaMug** [comment]
Use https://ci.codemc.org/job/PikaMug/job/Quests/23/ once available

**Warning:** The build linked above is experimental. Make sure to back up your Quests folder before attempting to use it. Alternatively, wait until the final release on Spigot.

**Comment by brnxx** [comment]
![image](https://user-images.githubusercontent.com/49076883/63377796-24ebed00-c367-11e9-8ecc-b14a6a0ec2c5.png)
![image](https://user-images.githubusercontent.com/49076883/63377825-36cd9000-c367-11e9-9a1e-153dd607b384.png)

**Comment by PikaMug** [comment]
That's technically a different, albeit related error.

Use https://ci.codemc.org/job/PikaMug/job/Quests/25/ once available

**Warning:** The build linked above is experimental. Make sure to back up your Quests folder before attempting to use it. Alternatively, wait until the final release on Spigot.
